sim/mahasiswa/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from sim.mahasiswa.forms import mahasiswa_F, loginmahasiswa_F, editmahasiswa_F, pengaduan_F, editpengaduan_F
from sim.models import Tmahasiswa, Tpengaduan
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image


rmahasiswa = Blueprint('rmahasiswa',__name__)

@rmahasiswa.route("/")
def home():
    return render_template("home.html",)

@rmahasiswa.route("/about")
def about():
    return render_template("about.html")

@rmahasiswa.route("/data_mahasiswa", methods =['GET','POST'])
def data_m():
    form=mahasiswa_F()
    if form.validate_on_submit():
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_mahasiswa=Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data, 
        password=pass_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun- {form.npm.data} berhasil daftar','warning')
        return redirect(url_for('rmahasiswa.login_mahasiswa'))
    return render_template("data-mahasiswa.html", form=form)
    
@rmahasiswa.route("/login_mahasiswa", methods =['GET','POST'])
def login_mahasiswa():
    if current_user.is_authenticated:
        return redirect(url_for('rmahasiswa.home'))
    form=loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm=Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('Selamat Datang Kembali', 'warning')
            return redirect(url_for('rmahasiswa.akunmahasiswa'))
        else:
            flash('Login Gagal, Periksa NPM dan Password Kembali', 'denger')
    return render_template("login_mahasiswa.html", form=form)

@rmahasiswa.route("/akunmahasiswa")
@login_required
def akunmahasiswa():
    return render_template('akunmahasiswa.html')

@rmahasiswa.route("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('rmahasiswa.home'))


#simpanfoto
def simpan_foto(form_foto):
    random_hex=secrets.token_hex(8)
    f_name, f_ext= os.path.splitext(form_foto.filename)
    foto_fn=random_hex + f_ext
    foto_path=os.path.join(app.root_path, 'sim/static/foto', foto_fn)
    ubah_size=(300,300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn

@rmahasiswa.route("/edit_mahasiswa", methods=['GET', 'POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto=file_foto
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        current_user.password=pass_hash
        db.session.commit()
        flash('Data Berhasil diubah','warning')
        return redirect(url_for('rmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
        form.npm.data=current_user.npm
        form.nama.data=current_user.nama
        form.email.data=current_user.emails
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat
    return render_template('edit_mahasiswa.html', form=form) 

@rmahasiswa.route("/pengaduan", methods=['GET', 'POST'])
@login_required
def pengaduan():
    dt_pengaduan=Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pengaduan=Tpengaduan(subjek=form.subjek.data, kategori=form.kategori.data, detail_pengaduan=form.detail_pengaduan.data, mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data Berhasil ditambah', 'warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template('pengaduan.html',form=form, dt_pengaduan=dt_pengaduan)

@rmahasiswa.route("/pengaduan/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pengaduan(ed_id):
    form=editpengaduan_F() #registrasi form "editpengaduan_F"
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)#cari tahu 404??
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan
    elif form.validate_on_submit():
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.kategori=form.kategori.data
        dt_pengaduan.detail_pengaduan=form.detail_pengaduan.data
        db.session.commit()
        flash('Data Berhasil di edit', 'warning')
        return redirect(url_for('rmahasiswa.pengaduan'))

    return render_template('edit_pengaduan.html', form=form)#form=form(menampilkan edit pengaduan yang berdasarkan form yang telah diregistrasi)

@rmahasiswa.route("/delete/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pengaduan(id):
    h_pengaduan= Tpengaduan.query.get(id)
    db.session.delete(h_pengaduan)
    db.session.commit()
    flash('Data berhasil dihapus', 'warning')
    return redirect(url_for('rmahasiswa.pengaduan'))

@rmahasiswa.route("/pengaduan/<int:ed_id>/detail", methods=['GET', 'POST'])
@login_required
def detail_pengaduan(ed_id):
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    return render_template('detail_pengaduan.html', dt_pengaduan=dt_pengaduan)

if __name__ =="__main__":
    app.run(debug=True)

sim/templates/about.html
{% extends "base.html"%}

{% block konten %}
<h1>tentang kami</h1>
<p>selamat datang pada halaman about</p>
{% for data in data_susel %}
<h2 style="font-style: oblique;font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">Data Kawal Corona Sumatera selatan :</h2>
<p>Positif : <b>{{data.Kasus_Posi}}</b></p>
<p>Sembuh : <b>{{data.Kasus_Semb}}</b></p>
<p>Meninggal : <b>{{data.Kasus_Meni}}</b></p>

{% endfor %}
{% endblock %}

sim/templates/akunmahasiswa.html
{% extends "base.html"%}

{% block konten %}
<div class="jumbotron">
    
    <h1 class="display-4">Hello, {{current_user.nama}}!</h1>
    <p class="lead">Selamat datang disistem informasi Pengaduan, semoga segala pengaduan anda menjadi perbaikan kami.</p>
    <hr class="my-4">
    <p>Klik untuk memulai pengaduan anda</p>
    <a class="btn btn-warning btn-lg" href="{{url_for('rmahasiswa.pengaduan')}}" role="button">pengaduan</a>
  </div>
{% endblock %}

sim/templates/base.html
 <html>
    <head>
        <title>selamat datang</title>
        <link rel="stylesheet" href='{{ url_for('static', filename="css/bootstrap.min.css")}}' integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href='{{ url_for('static', filename="css/style.css")}}'>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <div class="container">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{{url_for('rmahasiswa.home')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{url_for('rmahasiswa.about')}}">about</a>
                </li>
                {% if current_user.is_authenticated %}
                {% else %}
                <li class="nav-item dropdown">
                  <a class="nav-link" href="{{url_for('rmahasiswa.login_mahasiswa')}}">Login Mahasiswa<span class="sr-only">(current)</span></a>
                 </li>
                 {% endif %}
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
        </div>
          </nav>
       <div class="konten">
        <div class="container mt-4">
            <div class="row">
                <div class="col-md-8">
                    <div class="shadow p-3 mb-5 bg-white rounded">
                      <!--flash-->
                      {% with messages= get_flashed_messages(with_categories=true) %}
                      {% if messages %}
                      {% for category, message in messages %}
                      
                      <div class="aler alert-{{category}}">
                            {{massage}}
                      </div>
                      {% endfor %}
                      {% endif %}
                      {% endwith %}

                    <p>selamat datang</p>
                    <p>hallo semua selamat datang kembali diwebsite ini</p>
                    {% block konten %}

                    {% endblock %}
                </div>
                </div>
                <div class="col-md-4">
                    <div class="shadow p-3 mb-5 bg-white rounded">
                    {% if current_user.is_authenticated %}
                    <div class="card" style="width: 20rem;">
                    <img src="{{url_for('static', filename='foto/' + current_user.foto)}}" class="card-img-top" alt="">
                    <div class="card-body">
                      <h5 class="card-title">{{current_user.nama}}</h5>
                      <p class="card-text">{{current_user.email}}</p>
                    </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.akunmahasiswa')}}">Dasboard</a></li>
                    <li class="list-group-item">Dapibus ac facilitisi in</li>
                    <li class="list-group-item">Vestibulon at eros</li>
                  </ul>
                  <div class="card-body">
                    <a href="{{url_for('rmahasiswa.edit_mahasiswa')}}" class="card-link">Update Profil</a>
                    <a href="{{url_for('rmahasiswa.logout_mahasiswa')}}" class="card-link">Logout</a>
                  </div>
                </div>
                    {% else %}
                    <h1>Menu Lain</h1>
                    <li>Data Mahasiswa</li>
                    <li>Data Dosen</li>
                    {% endif %}
                    
                </div>
                </div>
            </div>
            </div>
       </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src='static/js/bootstrap.min.js' integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

sim/templates/data-mahasiswa.html
{% extends "base.html" %}

{% block konten %}

<h1>Data Akun</h1>
<form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group"> 
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
            {{form.npm(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.npm.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.npm(class="form-control")}}
        {% endif %}
    </div>
    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
            {{form.email(class="form-control is-invalid")}}
        <div class="invalid-feedback">
             {% for error in form.email.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}
             {{form.email(class="form-control")}}
        {%endif%}
    </div>
    <div class="form-group">
        {{form.kelas.label(class="form-control-label")}}
        {{form.kelas(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.alamat.label(class="form-control-label")}}
        {{form.alamat(class="form-control")}}
    </div>

    <div class="form-group"> 
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.password(class="form-control")}}
        {% endif %}
    </div>


    <div class="form-group"> 
        {{form.konf_pass.label(class="form-control-label")}}
        {% if form.konf_pass.errors %}
            {{form.konf_pass(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.konf_pass.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.konf_pass(class="form-control")}}
        {% endif %}
    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
  </form>
 
{% endblock %}

sim/templates/detail.html
{% extends "base.html"%}

{% block konten %}
<tbody>
    {% for data in dt_pengaduan %}
  <tr>
    <td><a href="detail.html" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit">#</a></td>
    <td>{{data.tgl_post}}</td>
    <td>{{data.subjek}}</td>
    <td>{{data.kategori}}</td>
    <td>{{data.detail_pengaduan}}</td>
    <td>{{data.mahasiswa_id}} / {{data.mahasiswa.nama}}</td>
    <td><a href="" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit">Edit</a></td>
    <td><a href="" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit">Hapus</a></td>
    
  </tr>
  {% endfor %}
</tbody>
{% endblock %}

sim/templates/detail_pengaduan.html
{% extends "base.html"%}

{% block konten %}
<h3>Detail Pengaduan</h3>
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Hallo selamat datang</h4>
    <hr>
    <table class="table table-hover">
        <tr>
            <td>NPM</td>
            <td>{{dt_pengaduan.mahasiswa.npm}}</td>
        </tr>
        <tr>
            <td>Nama</td>
            <td>{{dt_pengaduan.mahasiswa.nama}}</td>
        </tr>
        <tr>
            <td>Kelas</td>
            <td>{{dt_pengaduan.mahasiswa.kelas}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{dt_pengaduan.mahasiswa.email}}</td>
        </tr>
        <tr>
            <td>alamat</td>
            <td>{{dt_pengaduan.mahasiswa.alamat}}</td>
        </tr>
    </table>
  </div>
  <div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Data Pengaduan</h4>
    <hr>
    <p class="mb-0"></p>

    <table class="table table-hover">
        <tr>
            <td>Tgl Post</td>
            <td>{{dt_pengaduan.tgl_post}}</td>
        </tr>
        <tr>
            <td>subjek</td>
            <td>{{dt_pengaduan.subjek}}</td>
        </tr>
        <tr>
            <td>kategori</td>
            <td>{{dt_pengaduan.kategori}}</td>
        </tr>
        <tr>
            <td>Pengaduan :</td>
        </tr>
        <tr>
            <td>{{dt_pengaduan.detail_pengaduan}}</td>
        </tr>
    </table>
  </div>
  <a class="btn btn-warning" href="{{url_for('rmahasiswa.pengaduan')}}">Kembali</a>
{% endblock %}

 

sim/templates/edit_mahasiswa.html
{% extends "base.html" %}

{% block konten %}

<h1>Update Data Profil</h1>
<form method="POST" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <div class="form-group"> 
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
            {{form.npm(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.npm.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.npm(class="form-control")}}
        {% endif %}
    </div>
    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
            {{form.email(class="form-control is-invalid")}}
        <div class="invalid-feedback">
             {% for error in form.email.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}
             {{form.email(class="form-control")}}
        {%endif%}
    </div>
    <div class="form-group">
        {{form.kelas.label(class="form-control-label")}}
        {{form.kelas(class="form-control")}}
    </div>
    <div class="form-group">
        {{form.alamat.label(class="form-control-label")}}
        {{form.alamat(class="form-control")}}
    </div>

    <div class="form-group"> 
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.password(class="form-control")}}
        {% endif %}
    </div>


    <div class="form-group"> 
        {{form.konf_pass.label(class="form-control-label")}}
        {% if form.konf_pass.errors %}
            {{form.konf_pass(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.konf_pass.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.konf_pass(class="form-control")}}
        {% endif %}
    </div>

    <div class="form-group"> 
        {{form.foto.label(class="form-control-label")}}
        {% if form.foto.errors %}
            {{form.foto(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.foto.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.foto(class="form-control")}}
        {% endif %}
    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
  </form>
 
{% endblock %}

sim/templates/edit_pengaduan.html
{% extends "base.html" %}

{% block konten %}
<div class="jumbotron">
    <h3>Edit Pengaduan</h3>
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group"> 
            {{form.subjek.label(class="form-control-label")}}
            {% if form.subjek.errors %}
                {{form.subjek(class="form-control is-invalid")}}
    
            <div class="invalid-feedback">
                {% for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% else %}
                {{form.subjek(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group"> 
            {{form.kategori.label(class="form-control-label")}}
            {% if form.kategori.errors %}
                {{form.kategori(class="form-control is-invalid")}}
    
            <div class="invalid-feedback">
                {% for error in form.kategori.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% else %}
                {{form.kategori(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group"> 
            {{form.detail_pengaduan.label(class="form-control-label")}}
            {% if form.detail_pengaduan.errors %}
                {{form.detail_pengaduan(class="form-control is-invalid")}}
    
            <div class="invalid-feedback">
                {% for error in form.detail_pengaduan.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% else %}
                {{form.detail_pengaduan(class="form-control")}}
            {% endif %}
        </div>
        
        <div class="form-group">
            {{form.submit(class="btn btn-warning")}}
            <a class="btn btn-secondary" href="{{url_for('rmahasiswa.pengaduan')}}">Kembali</a>
        </div>   
      </form>
</div>
{% endblock %}

sim/templates/home.html
{% extends "base.html"%}

{% block konten %}
<div class="jumbotron">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </div>
{% endblock %}

sim/templates/login_mahasiswa.html
{% extends "base.html" %}

{% block konten %}

<h1>Login Mahasiswa</h1>
<form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group"> 
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
            {{form.npm(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.npm.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.npm(class="form-control")}}
        {% endif %}
    </div>
  
    <div class="form-group"> 
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
            {{form.password(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {% else %}
            {{form.password(class="form-control")}}
        {% endif %}
    </div>

    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
    <span> <a href="{{url_for('rmahasiswa.data_m')}}">Daftar Akun</a></span>

  </form>
 
{% endblock %}

sim/templates/pengaduan.html
{% extends "base.html" %}

{% block konten %}
<div class="jumbotron">
    
    <h3>pengaduan</h3>
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group"> 
            {{form.subjek.label(class="form-control-label")}}
            {% if form.subjek.errors %}
                {{form.subjek(class="form-control is-invalid")}}
    
            <div class="invalid-feedback">
                {% for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% else %}
                {{form.subjek(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group"> 
            {{form.kategori.label(class="form-control-label")}}
            {% if form.kategori.errors %}
                {{form.kategori(class="form-control is-invalid")}}
    
            <div class="invalid-feedback">
                {% for error in form.kategori.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% else %}
                {{form.kategori(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group"> 
            {{form.detail_pengaduan.label(class="form-control-label")}}
            {% if form.detail_pengaduan.errors %}
                {{form.detail_pengaduan(class="form-control is-invalid")}}
    
            <div class="invalid-feedback">
                {% for error in form.detail_pengaduan.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {% else %}
                {{form.detail_pengaduan(class="form-control")}}
            {% endif %}
        </div>
        
        <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
        </div>
        
      </form>
      <hr class="display-4">
      <h4>Data Pengaduan</h4> 
      <table class="table table-responsive table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Tanggal</th>
            <th scope="col">subjek</th>
            <th scope="col">kategori</th>
            <th scope="col">edit</th>
            <th scope="col">hapus</th>
          </tr>
        </thead>
        <tbody>
            {% for data in dt_pengaduan %}
          <tr>
            <td scope="row">
                <a href="{{url_for('rmahasiswa.detail_pengaduan', ed_id=data.id)}}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1H3.707l10.147 10.146a.5.5 0 0 1-.708.708L3 3.707V8.5a.5.5 0 0 1-1 0v-6z"/>
                      </svg>
                </a>
            </td>
            <td>{{data.tgl_post}}</td>
            <td>{{data.subjek}}</td>
            <td>{{data.kategori}}</td>
            <td><a href="{{url_for('rmahasiswa.update_pengaduan', ed_id=data.id)}}" class="btn btn-warning btn-xs" >Edit</a></td> 
            <td><a href="/delete/{{data.id}}" onclick="return confirm('Yakin data dihapus?')" class="btn btn-danger btn-xs">Hapus</a></td>
            
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
  </div>
   
   
{% endblock %}